# version: '3'
# services:
#   # my-app:
#   # image: ${docker-registry}/my-app:1.0
#   # ports:
#   # - 3000:3000
#   mongodb:
#     image: mongo
#     ports:
#       - 27017:27017
#     environment:
#       - MONGO_DB_USERNAME=user
#       - MONGO_DB_PASSWORD=password
#       - MONGO_DB_HOST=localhost
#       - MONGO_DB_PORT=27017
#       - MONGO_DB_DATABASE=testdata
#     volumes:
#       - mongo-data:/data/db
# volumes:
#   mongo-data:
#     driver: local



version: "3"
services:
       app:
           container_name: xapp
           image: xapp
           restart: always
           build: .
           ports:
             - "3005:3005"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - mongo_db:/data/db
             ports:
               - '27017:27017'


volumes:
  mongo_db: {}